### ISSUE TITLE
[CLOSED] Last Line Of Module

### ISSUE THREAD

**Issue by R0bl0x10501050** [FBanTeam/FBan#2]
Change the last line of the module to
```lua
return FBan
```
as `return` by itself will not work.

**Comment by FBanTeam** [comment]
Alright. I am currently fixing your issue.

**Comment by FBanTeam** [comment]
For me I clearly see it's have `return FBan`. Are you sure of this report? @R0bl0x10501050

**Comment by FBanTeam** [comment]
If you want proof.

https://prnt.sc/112np0p

**Comment by FBanTeam** [comment]
Please make sure before posting bug reports your case is real. I have checked the module and this is a fake report. Next time please check the module before providing a bug report.
